import Head from 'next/head'
import { useReducer } from 'react';
import { rootReducer, initialState } from '../store';
import { Board } from '../widgets/Board';

export default function Home() {
  
  const [state, dispatch] = useReducer(rootReducer, initialState);
  return (
    <div>
      <Head>
        <title>Productivity App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      <Board
        board={state.board.list[0]}
        dispatch={dispatch}
      />
   
    </div>
  )
}
